# Gather rpm package facts
- name: Gather rpm package facts
  package_facts:
    manager: auto

# Install Java
- name: Install Java
  apt: 
    name: default-jre
    update_cache: yes
  when: "'default-jre' not in ansible_facts.packages"

- name: Unhold logstash version for install
  command: apt-mark unhold logstash
  changed_when: false

# Install Logstash
- name: Install logstash
  apt:
    name: logstash
    update_cache: yes
  when: "'logstash' not in ansible_facts.packages"

- name: Hold logstash version
  command: apt-mark hold logstash
  when: elastic_stack_version_lock
  changed_when: false
    
# Configure logstash
- name: Create logstash configuration file
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item | basename | regex_replace('^(.*).j2$', '\\1' ) }}"
  loop: "{{ logstash_config_files }}"
  notify: restart logstash

# Ensure logstash is started
- name: Start logstash
  service:
    name: logstash
    state: started
    enabled: true
  
  
